spring:
  jpa:
    show-sql: true
  datasource:
    password: 12345678
    url: jdbc:mysql://172.18.0.1:3306/ecommerce?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: ecommerce
  data:
    redis:
      username:
      password: hgs637#@x9
      host: 127.0.0.1
      port: 7963

  thymeleaf:
    cache: false
  web:
    resources:
      chain:
        cache: false
sentry:
  environment: dev